### ISSUE TITLE
Add Awesome logo.

### ISSUE THREAD

**Issue by iCHAIT** [iCHAIT/awesome-macOS#32]
It would be nice to have an awesome logo for this repository.

**Comment by filippoferraris** [comment]
Cool idea. I'll be very happy to help on this! 
I've designed the logo of [my company](http://enerbrain.com/) recently and I can work on one in my free time!

@iCHAIT can an you give me a little brief, if you have anything in mind? Or may i go wild, and post here few ideas after the weekend?

**Comment by filippoferraris** [comment]
ps: just a test after playing 10 min with the OSX logo / bg / apple logo...:

![awesomeosx-logo---lowres](https://cloud.githubusercontent.com/assets/1977040/10058174/6481f352-6244-11e5-947f-951c0a19822c.png)

decent enough?

**Comment by herrbischoff** [comment]
I believe it should absolutely not contain an Apple logo, as Apple is notorious for strictly enforcing its [Copyright and Trademark guidelines](https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html):

> Developers may use Apple, Macintosh, iMac, or any other Apple word mark (but not the Apple Logo or other Apple-owned graphic symbol/logo) in a referential phrase on packaging or promotional/advertising materials to describe that the third party product is compatible with the referenced Apple product or technology [...]

Other than that, my impression is that it looks kind of cheapish, not awesome. Any kind of strong gradient, mixing elements (Apple logo/star) or incoherent use of typography will produce such a result. Also, it's spelled OS X, not OSX — for Operating System Ten.

Besides, I'm not sure if the currently implemented text logo may be what this was about. @iCHAIT, what were/are your intentions with this issue?

**Comment by filippoferraris** [comment]
agree @herrbischoff, it was just a fast play-over-apple-logo-thing done in 10 min, extremely cliche and quite bad... mainly to say: "hey let's have / develop / evolve a proper brief !"
I don't think any good logo could come out from 10 min play by a non-professional designer (me).

As there are many directions where this could go, only a proper brief can bring the path towards real awesomeness and a professional work!

If this can be of any inspiration... ;)
![simplicityad](https://cloud.githubusercontent.com/assets/1977040/10061597/81ae1eae-625a-11e5-8d59-885ddfa8d116.jpg)

**Comment by herrbischoff** [comment]
@filippoferraris: Ahh, the [McDonald's Theory approach](https://medium.com/@ienjoy/mcdonalds-theory-9216e1c9da7d). BTW: Nice poster find! :)

I suggest we wait for @iCHAIT letting us know what his original intention was.

**Comment by iCHAIT** [comment]
Honestly, it is a bit difficult to describe it in words, 

But this is how I imagined it to be -

We have an image of the back side of a Macbook Air/Pro showcasing an apple logo (as it does), but this entire logo would be kind of retro(ish). I know it would be difficult to relate to this, I'll try to depict this through some a suitable image if I can.

**Comment by herrbischoff** [comment]
@iCHAIT: Do you envision that logo idea being more of an image or more of a stylized graphic? Also, my objections regarding the use of an actual Apple logo still stand. Apple is known to defend its trademarks very aggressively.

**Comment by iCHAIT** [comment]
@herrbischoff  I visualize it as being a subtle and simple graphical logo and I am not interested in having the actual apple logo or any of its variations as the lists logo. Unfortunately, I have not found time to work on this :(
