### ISSUE TITLE
Maintainers Required

### ISSUE THREAD

**Issue by dkhamsing** [iCHAIT/awesome-macOS#326]
Hey @iCHAIT 
I see a lot of open pull requests..

Do you need help to maintain this list?
I or other volunteers would be glad to help

Feel free to close this if you're all set

**Comment by iCHAIT** [comment]
@dkhamsing Interestingly, I was about to open a similar issue myself, I would appreciate any help I can get to maintain this list further. Should I add you as a collaborator?

@herrbischoff Hi, can you help with this as well? You have been one of the most active contributors to the list and it would be great if you could help to maintain the list, can you take some time out for this?

**Comment by dkhamsing** [comment]
Yea I would be glad to help

**Comment by iCHAIT** [comment]
@dkhamsing I have sent you a request.

**Comment by dkhamsing** [comment]
Closing

@herrbischoff hope you have time to help!

**Comment by herrbischoff** [comment]
@iCHAIT: I'll be happy to help, collaborate me away. :)
