### ISSUE TITLE
Add MWeb

### ISSUE THREAD

**Issue by oimotis** [iCHAIT/awesome-macOS#341]
MWeb for Mac - Pro Markdown writing, note taking and static blog generator App

Official Site: http://www.mweb.im/
Mac App Store: https://itunes.apple.com/us/app/mweb-pro-markdown-writing/id954188948?ls=1&mt=12

![](http://www.mweb.im/asset/img/en/1-1.jpg)
![](http://www.mweb.im/asset/img/en/1-3.jpg)

**Comment by iCHAIT** [comment]
Please open a PR for your suggestion.
