### ISSUE TITLE
Kindly Consider Removing the mplayerX. it has PUP.Malware

### ISSUE THREAD

**Issue by debpalash** [iCHAIT/awesome-macOS#351]
http://imgur.com/IpaXoZK

**Comment by dkhamsing** [comment]
Thx for the report!

**Comment by herrbischoff** [comment]
Confirmed: https://www.virustotal.com/en/file/8a62217ee4f9b373415197480e167864d01482d05ff71493b15fa79a0e0ded14/analysis/

**Comment by iCHAIT** [comment]
Thanks for reporting @debpalash :)

**Comment by debpalash** [comment]
@iCHAIT  pleasure 😃
