### ISSUE TITLE
Update littleflocker

### ISSUE THREAD

**Issue by dkhamsing** [iCHAIT/awesome-macOS#361]
@vassyz let us know littleflocker is now a commercial product

Is it ok to keep (and update) or should we remove

---

Added in #360, we can revert the pull request to remove

**Comment by vassyz** [comment]
The GitHub link should be removed. The repo has [been made private](https://twitter.com/JZdziarski/status/777490501650055168), and Little Flocker is now a [commercial product](http://www.littleflocker.com/) (currently in Beta). Or you can change the URL. I'm not sure what your policy on Beta software is.

**Comment by dkhamsing** [comment]
@vassyz thanks! 

I will consult with others

**Comment by dkhamsing** [comment]
@iCHAIT @herrbischoff hey guys, what do you think

**Comment by iCHAIT** [comment]
@dkhamsing I think it should be removed from the list, and I believe @herrbischoff will concur.

For anyone looking for the reasons I would reckon reading comment written by @herrbischoff himself that sounds perfect to me.

Also,

> OSS community is too disparaging.

This is not cool. :/

**Comment by herrbischoff** [comment]
I am 100% behind this. Removing source code when going commercial: https://twitter.com/herrbischoff/status/779361543570022400
