### ISSUE TITLE
Criteria for list

### ISSUE THREAD

**Issue by z3t0** [iCHAIT/awesome-macOS#369]
Hi,

I was just scrolling through the list and although I found there are quite a lot of super cool things, what is the criteria for things to make it onto this list?

**Comment by iCHAIT** [comment]
Hey,

This list is a subset of a larger project [awesome](https://github.com/sindresorhus/awesome), so essentially this list tries to adhere to the awesome manifesto and rules mentioned in that project as closely as possible.

For more details you can read awesome manifesto and contribution guidelines in the repository I linked above.

On the outset -

We tend to include applications that are really awesome, by awesome I mean that the application or software you are suggesting should work flawlessly, should posses great features , have a reasonable active development community and user base, is a matured product in itself, and other contributors/developers/users can personally recommend that application/software.

If you feel any of the existing application on the list is not awesome and does not deserve to be on the list please feel free to open a PR removing that application, and the list maintainers will review it. Same goes if you wanna suggest some new additions to the list :smile:

**Comment by z3t0** [comment]
Thanks
