### ISSUE TITLE
AppWage

### ISSUE THREAD

**Issue by dkhamsing** [iCHAIT/awesome-macOS#385]
Status: let's check back in Dec/Jan and see the progress of the app

---
This looks pretty good https://github.com/hankinsoft/AppWage

what do you think

@iCHAIT 
@herrbischoff

**Comment by herrbischoff** [comment]
Looks promising. But why do so many OSS authors not care about a proper UI? The icons on the top left are just hideous (and over-cropped), the sidebar is not properly sized for the content it is supposed to display, the list view is claustrophobic and all in all it looks more like a Windows application made to resemble a macOS one.

Also, as there is no release yet, maybe we should hold addition for now and look where it's moving. It's only about 6 weeks old, which could explain the inconsistencies.

**Comment by dkhamsing** [comment]
@herrbischoff there was no significant change.. should we close this?

**Comment by iCHAIT** [comment]
@dkhamsing I think this can be closed.
