### ISSUE TITLE
SnapMotion, ScreenToLayers and VideoToolbox

### ISSUE THREAD

**Issue by jeremyvizzini** [iCHAIT/awesome-macOS#387]
Hi,

I am a mac apps developper and I think some of my apps could be add to the list.

ScreenToLayers : open-source mac app to save your screen as a layered psd.
[http://www.screentolayersapp.com](http://www.screentolayersapp.com)
[http://github.com/jeremyvizzini/ScreenToLayers](http://github.com/jeremyvizzini/ScreenToLayers)

SnapMotion : mac app to extract images from video
[http://www.snapmotionapp.com](http://www.snapmotionapp.com)

VideoToolbox : mac app to extract images, informations, metadata and others from video.
[http://www.videotoolboxapp.com](http://www.videotoolboxapp.com)

**Comment by iCHAIT** [comment]
HI @jeremyvizzini, thanks for the suggestions, but please open a separate Pull Request for each of your suggestion, as it would be easier to review/directly merge. Closing this issue.
