### ISSUE TITLE
Add some popular dotfiles

### ISSUE THREAD

**Issue by Haroenv** [iCHAIT/awesome-macOS#390]
https://github.com/mathiasbynens/dotfiles would be the first (also partly under setup)

**Comment by iCHAIT** [comment]
I think this would be a better prospect for [awesome-dotfiles](https://github.com/webpro/awesome-dotfiles).

**Comment by Haroenv** [comment]
It's already in there. What about linking .osx of that repo specifically here?

**Comment by herrbischoff** [comment]
This is already widely known and will not have to be included in all and every Mac list. Also, there's [herrbischoff/awesome-osx-command-line](https://github.com/herrbischoff/awesome-osx-command-line) which should contain everything found there plus more.
