### ISSUE TITLE
Chat app - Franz

### ISSUE THREAD

**Issue by bakman2** [iCHAIT/awesome-macOS#395]
multiclient including whatsapp

http://meetfranz.com

**Comment by iCHAIT** [comment]
Please open a pull request for your suggestion.
Thanks :)

**Comment by herrbischoff** [comment]
This was [previously rejected](https://github.com/iCHAIT/awesome-macOS/pull/276). @bakman2, please do not add a pull request.

**Comment by bakman2** [comment]
I read it was rejected for privacy reasons that could be hold against a number of applications on the current list, except for the web part. Yet, chitchat does the same except that it was written in xcode. 

It does not matter to me, just trying to help the readers of this list.

**Comment by herrbischoff** [comment]
Thank you for the suggestion in any case. Whatever the other reasons, Electron apps are not allowed on this list.

> Yet, chitchat does the same except that it was written in xcode.

This is a very important difference. Native apps are always preferred.

> rejected for privacy reasons that could be hold against a number of applications on the current list

Please point them out and I will investigate further. If any application is opaque about how the data is used and where it resides, that may be grounds for removal.
