### ISSUE TITLE
Deadlink to Hacky

### ISSUE THREAD

**Issue by 1024jp** [iCHAIT/awesome-macOS#411]
The link to the application Hacky (http://www.hackyapp.com/) seems dead. The GitHub repo still exists but it's also [not maitained for 3 years](https://github.com/eliaskg/Hacky).

I jsut made an issue instead of PR since I don't know you will remove the app from the list or just change the link target to GitHub (even it discontinued).

**Comment by herrbischoff** [comment]
I'd say open a pull request to remove it entirely, as it is not even available via Mac App Store any more.

**Comment by 1024jp** [comment]
@herrbischoff Ok, I've just made it #412.
