### ISSUE TITLE
stupid Mac List

### ISSUE THREAD

**Issue by EasonWang01** [iCHAIT/awesome-macOS#418]
Mac's quality getting worse.

QuickTime crash

<img width="782" alt="sss" src="https://cloud.githubusercontent.com/assets/11001914/24227487/5d076cb6-0fa8-11e7-8ed7-93e575de95d5.png">

SSD capacity bug

<img width="808" alt="2017-03-23 9 06 38" src="https://cloud.githubusercontent.com/assets/11001914/24227511/79540190-0fa8-11e7-9b4c-52e5e0e20613.png">

**Comment by herrbischoff** [comment]
@EasonWang01: This is considered spamming and flaming and has no place on GitHub. I have reported you to support. Goodbye.
