### ISSUE TITLE
new tools

### ISSUE THREAD

**Issue by cnstntn-kndrtv** [iCHAIT/awesome-macOS#442]
Hi. Can you add this tools to your list? 
https://github.com/cnstntn-kndrtv/open-in-buttons-for-finder-toolbar

**Comment by herrbischoff** [comment]
Contribution guidelines, read them.

**Comment by herrbischoff** [comment]
Also, those are simple Automator Workflows. There is **zero** reason why those should be available in binary form – apart from trying to spread malware or other undesirable stuff of course. To top things off, there is no source code, no guide to make your own ones and no way to download the app bundles properly.
