### ISSUE TITLE
Remove Amphetamine

### ISSUE THREAD

**Issue by notDavid** [iCHAIT/awesome-macOS#468]
Just an fyi, Amphetamine hasn't been updating in a few years, and no longer works on the latest 2 macOS major versions:  https://github.com/x74353/Amphetamine/issues/26

**Comment by dkhamsing** [comment]
Thx @notDavid @herrbischoff

**Comment by lebensterben** [comment]
@notDavid @dkhamsing Also mentioned in [x74353/Amphetamine#26](https://github.com/x74353/Amphetamine/issues/26), this seems to be a bug of macOS rather then the app itself. Though it's not been updated for a while, it still works on my macbook pro with High Sierra 10.13.2.

**Comment by lebensterben** [comment]
@notDavid @dkhamsing Also mentioned in x74353/Amphetamine#26, this seems to be a bug of macOS rather then the app itself. Though it's not been updated for a while, it still works on my macbook pro with High Sierra 10.13.2.

**Comment by notDavid** [comment]
Well, the person who commented says that caffeine doesn't work for him either, so that seems like a firmware issue indeed (which Apple has confirmed and can be solved with a SMC reset.)

However in my case caffeine and InsomniaX work fine, but Amphetamine doesn't. So that's clearly not a firmware / macOS issue.

The issue might be related to everyones different pmset / sleep settings. In any case, it doesn't seem like a reliable tool anymore.
