### ISSUE TITLE
Replace Bookmark Utilities category with News Readers

### ISSUE THREAD

**Issue by stackptr** [iCHAIT/awesome-macOS#477]
Currently, there are two news readers that are grouped in different categories: `ReadKit` is in Bookmark Utilities since it can manage Instapaper/Pocket, while `Vienna` is in Other probably because it is lacking that integration (I have not used it). If #475 is approved, a third full-featured news reader would be added.

I suggest grouping these apps, along with perhaps `hacker-menu` into the category News Readers, and move `Spillo` to Other, or alternatively keep it as the sole member of Bookmark Utilities.

I think it is ideal to keep the Other category as small as possible, as it is the proverbial junk drawer that makes finding relevant apps harder.

**Comment by iCHAIT** [comment]
Please open a Pull Request for your suggestion and it can be discussed further.
