### ISSUE TITLE
Replace Gas-mask with SwitchHosts?

### ISSUE THREAD

**Issue by notDavid** [iCHAIT/awesome-macOS#483]
fyi, [Gas-mask](https://github.com/2ndalpha/gasmask) doesn't work for me. I'm not sure if it's just me, or it's incompatible with High Sierra, but i see many issues reported in their Github repo.

In any case, [SwitchHosts](https://oldj.github.io/SwitchHosts/) seems a better alternative.
It also has an Alfred workflow :)

**Comment by iCHAIT** [comment]
Thanks for the suggestion, but open a PR if you would like to see any changes in the list. That'd be more helpful :)
