### ISSUE TITLE
Add VSCode in editors

### ISSUE THREAD

**Issue by anshumanv** [iCHAIT/awesome-macOS#510]
I think [vscode](https://code.visualstudio.com/) would make a valuable addition to the editors section.

**Comment by anshumanv** [comment]
Will send a PR if this is needed. 😃

**Comment by ajnsit** [comment]
Unfortunately, no Electron apps are allowed - https://github.com/iCHAIT/awesome-macOS/pull/368.

https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md

**Comment by anshumanv** [comment]
Ah my bad.
