### ISSUE TITLE
Suggestion: Bodega - stand-alone usage still works for checking all installed apps for Sparkle updates

### ISSUE THREAD

**Issue by steakknife** [iCHAIT/awesome-macOS#519]
https://mac.softpedia.com/get/Utilities/Bodega.shtml

Ignore the warning about being offline and click on applications.

The downside is it's not automatic (in checking) like that Windows program Secunia PSI was, once upon a time.

**Comment by iCHAIT** [comment]
Please open a Pull Request for your suggestion.
