### ISSUE TITLE
[Mac macOS Manual Pages] - Page not found

### ISSUE THREAD

**Issue by EvgenyKarkan** [iCHAIT/awesome-macOS#520]
This link seems to be not valid anymore
> Mac macOS Manual Pages - Apple's official man page reference which lists all general commands in Section 1.

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/

Clicking on it redirects to a blank web page ("The page you’re looking for can’t be found.")

**Comment by iCHAIT** [comment]
Fixed in fc1b45f087f7884242352f421ee210eeb2a8cf7e
