### ISSUE TITLE
Could we get Xn Convert on this list? It's free!

### ISSUE THREAD

**Issue by Danrancan** [iCHAIT/awesome-macOS#544]
Could we get [Xn Convert ](https://www.xnview.com/en/xnconvert/) on this list in the Photo editor section? This is an amazing app that pretty much does everything in post processing photos. From batch watermarking to batch renaming to cleaning metadata to adding effects all in batches, this app does everything you need for photo sets and batches of photos. Please add it as I am highly surprised it has been left out! I use it all the time and its great! Thanks.

[https://www.xnview.com/en/xnconvert/]

**Comment by herrbischoff** [comment]
Open a proper pull request and we will discuss it in the team. However, as this is a cross-platform application with the kind of clunky GUI that comes with it, the chances of inclusion are close to zero.
