### ISSUE TITLE
Link issues

### ISSUE THREAD

**Issue by dkhamsing** [iCHAIT/awesome-macOS#560]
> 1. [L086]  https://flawlessapp.io/ getaddrinfo: No address associated with hostname 
> 2. [L309] 404 https://bitbucket.org/kosovan/theunarchiver  

cc @herrbischoff 

Relates to #448 #444

**Comment by herrbischoff** [comment]
Well, The Unarchiver has turned closed source but is still quite useful, so I recommend changing the link to: https://theunarchiver.com

Flawless App appears to be another one that unceremoniously bites the dust and should be removed. Also, I'm increasingly fed up with commercial applications that get spun up by a small team just to disappear about three years later. At the very least not keeping your domain updated qualifies as grounds for removal in my book.
