### ISSUE TITLE
Suggestion: changelog, release, notification

### ISSUE THREAD

**Issue by notDavid** [iCHAIT/awesome-macOS#569]
Hi there, please consider adding a chronological 'changelog' once every few months and creating a [Release](https://docs.github.com/en/github/administering-a-repository/about-releases).

It's way easier and more accessible than going through the commit history to see recent additions :)
Also, people can then "Watch -> Custom -> Releases" to automatically get notified once every few months when new additions have been made :)

Maybe something like this, you get the idea...: https://github.com/notDavid/awesome-macOS/releases

Here is the markup in case you want to copy/paste:
<details>
<summary>Details</summary>

```
**2020-10**
\+ [RDM](https://github.com/avibrazil/RDM) - Easily set Mac Retina display to higher unsupported resolutions. [![Open-Source Software][OSS Icon]](https://github.com/avibrazil/RDM)
\+ [Recordia](https://sindresorhus.com/recordia) - Record audio directly from the menu bar or with a global keyboard shortcut.
\+ [Nova](https://nova.app/) - The beautiful, fast, flexible, native Mac code editor from Panic.

**2020-09**
\+ [iCMD](https://icmd.app) - Fuzzy menubar search and vim emulation. 
\- [Flawless App](https://flawlessapp.io/) - macOS tool for visual quality check of mobile app right inside iOS simulator.
\+ [MeetingBar](https://meetingbar.onrender.com) - Your meetings in MacOS status bar [![Open-Source Software][OSS Icon]](https://github.com/leits/MeetingBar) ![Freeware][Freeware Icon]

**2020-08**
\+ [Proxyman](https://proxyman.io) - High-performance man-in-the-middle proxy to observe and manipulate HTTP/HTTPS requests. ![Freeware][Freeware Icon]
\- [Arthur](http://arthur-osx.com/) - Safely optimize some of your Mac's hidden settings.
\+ [Sequel Ace](https://github.com/Sequel-Ace/Sequel-Ace) - A MySQL & MariaDB database manager. [![Open-Source Software][OSS Icon]](https://github.com/Sequel-Ace/Sequel-Ace) ![Freeware][Freeware Icon]

**2020-07**
\+ [Presentify](https://presentify.compzets.com) - Annotate anything on screen, be it, images, pdfs, videos, code, etc.
\+ [Jiffy](https://sindresorhus.com/jiffy) - Discover and share the best GIFs on GIPHY. ![Freeware][Freeware Icon]


[chitchat]: https://github.com/stonesam92/ChitChat
[OSS Icon]: https://cdn.rawgit.com/iCHAIT/awesome-osx/master/media/oss.svg
[Freeware Icon]: https://cdn.rawgit.com/iCHAIT/awesome-osx/master/media/free.svg
```

</details>

**Comment by iCHAIT** [comment]
@notDavid happy to add you as a collaborator if you are interested in working on this :)

**Comment by notDavid** [comment]
@iCHAIT Sure, glad to help 👍🏼

**Comment by iCHAIT** [comment]
Great @notDavid 

I have added you as a collaborator. I think you'll need to accept the invitation. Then you can go ahead and open a PR for the release I think. I am not very familiar with how Releases work on Github.

**Comment by notDavid** [comment]
Accepted, thank you!

I will have a look and add the releases soon (as shown in my first comment above), in the next few days.
Adding/updating a new release once every 3 months should be plenty i think…?

**Comment by iCHAIT** [comment]
Yep, once every 3 months should be a good start 👍

**Comment by iCHAIT** [comment]
Hi @notDavid any update on this?

**Comment by notDavid** [comment]
Hi @iCHAIT, sorry for the delay.

Let me know if you think the layout is okay (it’s saved as a draft currently), or if you want me to change anything: https://github.com/iCHAIT/awesome-macOS/releases

**Comment by iCHAIT** [comment]
Looks good to me.
@herrbischoff @dkhamsing guys, any feedback/ideas on this?

**Comment by herrbischoff** [comment]
LGTM

**Comment by notDavid** [comment]
> the reason for removal would be a nice addition

👍🏼
 

Are you sure you also want to remove the descriptions? For example when you sign up for “Repo > Watch > Custom > Releases” you will get notified by e-mail for new releases.

However when there’s no descriptions, and people see something like

  \+ krisp
  \+ swish
  \+ recodia

they have no clue if it might be of any use to them?

**Comment by herrbischoff** [comment]
> Also, I suggest skipping descriptions entirely **for changed and deleted entries**, only adding what was done to them.

For new entries the description should of course be there for the reason you stated.

**Comment by notDavid** [comment]
If everybody is happy i’ll close the issue and i’ll publish a new release this way, quarterly…

**Comment by iCHAIT** [comment]
Thank you all. Look forward to the quarterly releases. Thanks @notDavid for the help 😄
