### ISSUE TITLE
Link Issues

### ISSUE THREAD

**Issue by dkhamsing** [iCHAIT/awesome-macOS#578]
Found in #577
- https://github.com/etresoft/EtreCheck `404` 
- http://heliumfloats.com/ `Failed to open TCP connection to heliumfloats.com:80 (getaddrinfo: Name or service not known)`

**Comment by iCHAIT** [comment]
Fixed in 371d51d9a6108bf82a2bb24e2365cf79accbb8d8

Thanks @dkhamsing
