### ISSUE TITLE
Modification to ARHeadsetKit PR

### ISSUE THREAD

**Issue by philipturner** [iCHAIT/awesome-macOS#599]
Please don't block me from this repo for trying to reach out this way (like #dkhamsing did). I'm doing this instead of emailing @herrbischoff directly because it applies to all maintainers, including @LucasLarson, who already approved of my PR.

I acknowledge that ARHeadsetKit in its current form is kind of irrelevant to macOS. The utilities are useful, but it would be awkward to add an iOS-centric framework to iCHAIT/awesome-macOS.

I may separate out the utility functions into a framework called `ARHeadsetKit-Utilities` (or something else) in the near future. This exclusively includes the Metal extensions (and simd, Core Text, etc.), and will be used in [DL4S](https://github.com/palle-k/DL4S) (check out its only open issue for context). This should solve the concerns you are having, because then it would be clearly "related to macOS". @herrbischoff, what do you think about this?

You could delay accepting my PR, or close it but restore my ability to add comments. When I do make this hypothetical framework, I would comment or re-open the PR so you could reconsider.

Again, please don't treat me like #dkhamsing did for trying to resolve this situation.

**Comment by philipturner** [comment]
Update: I'm in the middle of making `ARHeadsetUtil`, please give me time to finish before doing anything

**Comment by philipturner** [comment]
[ARHeadsetUtil](https://github.com/philipturner/ARHeadsetUtil) is finished. @herrbischoff, please look at its README and judge for yourself whether it is relevant to macOS. If you approve, I assume that the pull request should go through.

Since I can't edit it, the initial commit still says ARHeadsetKit. However, I updated my branch for the merge, so ARHeadsetUtil will still be added to awesome-macOS.

**Comment by philipturner** [comment]
ARHeadsetUtil will be used during the development of [GPU acceleration](https://github.com/dl4s-contributors/dl4s-evolution) for [DL4S](https://github.com/palle-k/DL4S), the successor to Swift for TensorFlow. This is a macOS framework, which clearly proves ARHeadsetUtil's relevance to macOS.

**Comment by herrbischoff** [comment]
Do not open any more issues or pull requests regarding your project. I found it to not be relevant to this list and closed all pull requests.
