### ISSUE TITLE
Add Chat Clients

### ISSUE THREAD

**Issue by itsnotsaved** [iCHAIT/awesome-macOS#615]
- Zulip - Chat for distributed teams
https://zulip.com/apps/ https://zulip.com/apps/mac

- Mattermost - https://mattermost.com/
https://mattermost.com/download/

- Revolt Chat - Communication is critical, Privacy is essential.
https://revolt.chat/ https://github.com/revoltchat#download-links
https://github.com/revoltchat/desktop/releases

- RocketChat - https://rocket.chat/
https://github.com/RocketChat/Rocket.Chat.Electron https://rocket.chat/install#Apps

- Twake - https://twake.app/
https://github.com/linagora/Twake-Desktop

**Comment by herrbischoff** [comment]
Applications are considered when a pull request is sent. Also, without even checking, I bet all of those are Electron apps and therefore ineligible for inclusion. Please read the [contribution guidelines](https://github.com/iCHAIT/awesome-macOS/blob/master/.github/contributing.md). They exist for a reason.
